import os, re, json, subprocess, requests, sys, time
from google import genai
from google.oauth2.credentials import Credentials as YoutubeCredentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

def run_workflow():
    try:
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key: raise ValueError("❌ ไม่พบ API Key")
        
        client = genai.Client(api_key=api_key.strip())
        selected_model = 'models/gemini-2.5-flash'
        print(f"✅ ใช้โมเดล: {selected_model}")

        # 1. ร่างสคริปต์
        print("🧠 1. AI กำลังร่างเนื้อหา...")
        prompt = "สรุปเคล็ดลับการเงิน 3 ฉาก ตอบเป็น JSON: {\"topic\": \"...\", \"scenes\": [{\"text\": \"...\", \"image_prompt\": \"Cinematic, professional, finance, 4k\"}]}"
        response = client.models.generate_content(model=selected_model, contents=prompt)
        data = json.loads(re.search(r'\{.*\}', response.text, re.DOTALL).group())
        print(f"🎬 หัวข้อ: {data['topic']}")

        # 2. เสียงพากย์
        print("🎙️ 2. สร้างเสียงพากย์...")
        full_text = " ".join([s['text'] for s in data['scenes']])
        subprocess.run(f'edge-tts --voice "th-TH-NiwatNeural" --text "{full_text}" --write-media "v.mp3"', shell=True, check=True)

        # 3. ดาวน์โหลดภาพ (เพิ่มระบบสำรอง "ทุบกำแพง")
        print("🎨 3. กำลังดาวน์โหลดภาพประกอบ...")
        for i, sc in enumerate(data['scenes']):
            seed = int(time.time()) + i
            url = f"https://pollinations.ai/p/{sc['image_prompt'].replace(' ', '%20')}?width=1080&height=1920&model=flux&seed={seed}"
            
            success = False
            print(f"   📸 ฉากที่ {i+1}: กำลังโหลด...", end="")
            for attempt in range(3):
                try:
                    r = requests.get(url, timeout=30)
                    if r.status_code == 200 and len(r.content) > 10000:
                        with open(f"i_{i}.jpg", "wb") as f: f.write(r.content)
                        print(f" สำเร็จ")
                        success = True
                        break
                except: pass
                print(".", end="")
                time.sleep(2)
            
            # --- ระบบสำรองภาพ: ถ้าเว็บสร้างรูปล่ม ไม่ต้อง Raise Error ---
            if not success:
                print(f"\n   ⚠️ เว็บสร้างรูปล่ม, ใช้รูปสำรองสำหรับฉากที่ {i+1}")
                # ใช้รูปพื้นหลังเบลอๆ แบบง่ายๆ (Blurred background) ที่ชัวร์ว่ารันผ่าน
                fallback_url = "https://upload.wikimedia.org/wikipedia/commons/e/e0/Blurred_Image_01.jpg"
                try:
                    r_fallback = requests.get(fallback_url, timeout=30)
                    with open(f"i_{i}.jpg", "wb") as f: f.write(r_fallback.content)
                except:
                    # ถ้าโหลดรูปสำรองไม่ได้อีก ให้พังแบบรู้ตัว
                    raise RuntimeError(f"❌ โหลดทั้งรูป AI และรูปสำรองไม่สำเร็จสำหรับฉากที่ {i+1}")

        # 4. ประกอบวิดีโอ
        print("🎬 4. กำลังตัดต่อวิดีโอ...")
        with open("l.txt", "w") as f:
            for i in range(3):
                f.write(f"file 'i_{i}.jpg'\nduration 5\n")
            f.write(f"file 'i_2.jpg'")

        cmd = (
            "ffmpeg -y -f concat -safe 0 -i l.txt -i v.mp3 "
            "-c:v libx264 -pix_fmt yuv420p -r 25 -vf 'scale=1080:1920' "
            "-c:a aac -shortest final.mp4"
        )
        subprocess.run(cmd, shell=True, check=True)

        # 5. อัปโหลด
        print("🚀 5. อัปโหลดไป YouTube Studio...")
        with open('token.json', 'r') as f:
            creds = YoutubeCredentials.from_authorized_user_info(json.load(f))
        
        youtube = build("youtube", "v3", credentials=creds)
        request = youtube.videos().insert(
            part="snippet,status",
            body={
                "snippet": {"title": data['topic'], "description": "Auto-generated by AI"},
                "status": {"privacyStatus": "private"} # อัปโหลดเป็น Private ก่อน
            },
            media_body=MediaFileUpload("final.mp4")
        )
        res = request.execute()
        print(f"✨ สำเร็จแล้ว! คลิปของคุณอยู่ที่: https://youtu.be/{res['id']}")

    except Exception as e:
        print(f"\n‼️ พังตรงนี้ครับ: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    run_workflow()
