import os, re, json, subprocess, requests, sys, time, random
from google import genai
from google.oauth2.credentials import Credentials as YoutubeCredentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from PIL import Image, ImageDraw

# --- CONFIGURATION ---
MODEL_ID = 'models/gemini-2.5-flash'
SCENE_COUNT = 6
SCENE_DURATION = 10 
VIDEO_PRIVACY = "private"

def create_graphic_engine_image(path, text, scene_num, title_text):
    """สร้างภาพ Cinematic Minimalist (Gold-Black) ขึ้นมาเองด้วยโค้ด 100%"""
    print(f"   ⏳ ฉากที่ {scene_num}: กำลังเนรมิตภาพกราฟิกขลังๆ...")
    img = Image.new('RGB', (1080, 1920), color=(5, 5, 10))
    d = ImageDraw.Draw(img)
    
    # วาดกรอบหรูๆ Cinematic
    d.rectangle([40, 40, 1040, 1880], outline=(212, 175, 55), width=15)
    
    # ใส่ข้อความไทย (ตัดคำสั้นๆ เพื่อให้ง่ายต่อการแสดงผล)
    # หมายเหตุ: ใน GitHub อาจไม่มีฟอนต์ไทย เราจะเน้นภาพประกอบที่รันผ่าน
    # หากอยากให้มีข้อความไทย จำเป็นต้องอัปโหลดไฟล์ .ttf ไปพร้อมกับโค้ด
    text_fallback = f"LEGEND SCENE {scene_num}\n{text[:30]}..."
    
    # ตำแหน่งและสีข้อความ
    margin_text = 100
    pos_title = (margin_text, margin_text - 30)
    pos_body = (margin_text, 960)
    pos_footer = (margin_text, 1800)
    
    # ใส่ข้อความภาษาอังกฤษจำลองธีม (Fallback)
    d.text(pos_title, f">> M A S C O T   S T O R Y <<", fill=(212, 175, 55))
    d.text(pos_body, f"STORY SCENE {scene_num}", fill=(212, 175, 55))
    d.text(pos_footer, f"Auto-Generated by GITHUB & GEMINI", fill=(255, 255, 255, 150))
    
    # ใส่จุดเรืองแสงเป็น Mascot จำลอง (ปู่วอลลี่ตัวกลมๆ)
    d.ellipse([450, 700, 630, 880], fill=(50, 100, 255)) # ตัว
    d.ellipse([510, 770, 570, 830], fill=(255, 255, 255)) # ตา
    
    img.save(path, 'JPEG', quality=95)
    return True

def run_workflow():
    try:
        api_key = os.getenv("GEMINI_API_KEY")
        client = genai.Client(api_key=api_key.strip())
        
        # 1. ร่างบทมหากาพย์
        print("🧠 1. AI Director กำลังเขียนบทมหากาพย์ 60 วินาที...")
        prompt_system = (
            f"Create a 60s viral Thai storytelling script. {SCENE_COUNT} scenes. "
            "Thai voiceover. Detailed English visual prompts. "
            "Output STRICT JSON: {\"title\": \"...\", \"scenes\": [{\"text\": \"...\", \"visual\": \"Detailed English prompt\"}]}"
        )
        response = client.models.generate_content(model=MODEL_ID, contents=prompt_system)
        data = json.loads(re.search(r'\{.*\}', response.text, re.DOTALL).group())
        print(f"🎬 หัวข้อ: {data['title']}")

        # 2. เสียงพากย์
        print("🎙️ 2. สร้างเสียงพากย์ภาษาไทย...")
        full_text = " ".join([s['text'] for s in data['scenes'][:SCENE_COUNT]])
        subprocess.run(f'edge-tts --rate=-15% --voice "th-TH-NiwatNeural" --text "{full_text}" --write-media "v.mp3"', shell=True, check=True)

        # 3. สร้างรูปภาพกราฟิกอัตโนมัติ (High Reliability Mode)
        print("🎨 3. เข้าสู่กระบวนการเตรียมภาพประกอบด้วยโค้ด 100%...")
        scenes = data['scenes'][:SCENE_COUNT]
        for i, sc in enumerate(scenes):
            # เราใช้ฟังก์ชันใหม่ที่การันตีภาพมาแน่นอน
            create_graphic_engine_image(f"i_{i}.jpg", sc['visual'], i+1, data['title'])

        # 4. ตัดต่อ (ใส่ Effect ซูมขลังๆ)
        print("🎬 4. กำลังประกอบ Video ด้วยเทคนิค Cinematic Motion...")
        with open("l.txt", "w") as f:
            for i in range(len(scenes)):
                f.write(f"file 'i_{i}.jpg'\nduration {SCENE_DURATION}\n")
            f.write(f"file 'i_{SCENE_COUNT-1}.jpg'") # บรรทัดสุดท้ายเพื่อปิด loop

        # FFmpeg: ปรับ Scale และซูมขลังๆ สไตล์ Ken Burns
        cmd = (
            "ffmpeg -y -f concat -safe 0 -i l.txt -i v.mp3 "
            "-vf \"scale=1080:1920,setsar=1,zoompan=z='min(zoom+0.0015,1.5)':d=250:x='iw/2-(iw/zoom)/2':y='ih/2-(ih/zoom)/2':s=1080x1920\" "
            "-c:v libx264 -pix_fmt yuv420p -r 25 -c:a aac -shortest final.mp4"
        )
        subprocess.run(cmd, shell=True, check=True)

        # 5. อัปโหลด
        print(f"🚀 5. อัปโหลดสู่ YouTube (สถานะ: {VIDEO_PRIVACY})...")
        if not os.path.exists('token.json'):
            print("⚠️ ไม่พบ token.json ข้ามการอัปโหลด")
            return

        with open('token.json', 'r') as f:
            creds = YoutubeCredentials.from_authorized_user_info(json.load(f))
        
        youtube = build("youtube", "v3", credentials=creds)
        try:
            youtube.videos().insert(
                part="snippet,status",
                body={
                    "snippet": {"title": data['title'], "categoryId": "27"},
                    "status": {"privacyStatus": VIDEO_PRIVACY}
                },
                media_body=MediaFileUpload("final.mp4")
            ).execute()
            print("✨ ภารกิจสำเร็จ! เข้าไปตรวจงานใน YouTube Studio ของคุณได้เลย")
        except Exception as e:
            if "uploadLimitExceeded" in str(e): print("\n⚠️ Quota เต็ม! รอ 24 ชม.")
            else: raise e

    except Exception as e:
        print(f"\n‼️ พังตรงนี้: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    run_workflow()
