import os, re, json, subprocess, requests, sys, time
from google import genai
from google.oauth2.credentials import Credentials as YoutubeCredentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

def run_workflow():
    try:
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key: raise ValueError("❌ ไม่พบ API Key")
        
        client = genai.Client(api_key=api_key.strip())
        
        # เลือกโมเดลที่บัญชีคุณมี (Gemini 2.5 Flash)
        selected_model = 'models/gemini-2.5-flash'
        print(f"✅ ใช้โมเดล: {selected_model}")

        # 1. ร่างสคริปต์
        print("🧠 1. AI กำลังคิดบทพากย์และภาพประกอบ...")
        prompt = "Create a 3-scene YouTube Shorts script about Finance in Thai. Response ONLY JSON: {\"topic\": \"...\", \"scenes\": [{\"text\": \"...\", \"image_prompt\": \"Cinematic, professional, finance, 4k\"}]}"
        
        response = client.models.generate_content(model=selected_model, contents=prompt)
        data = json.loads(re.search(r'\{.*\}', response.text, re.DOTALL).group())
        print(f"🎬 หัวข้อ: {data['topic']}")

        # 2. เสียงพากย์
        print("🎙️ 2. กำลังสร้างเสียงพากย์...")
        full_text = " ".join([s['text'] for s in data['scenes']])
        subprocess.run(f'edge-tts --voice "th-TH-NiwatNeural" --text "{full_text}" --write-media "v.mp3"', shell=True, check=True)

        # 3. ดาวน์โหลดภาพ (เพิ่มระบบเช็คความถูกต้อง)
        print("🎨 3. กำลังดาวน์โหลดภาพประกอบ...")
        for i, sc in enumerate(data['scenes']):
            # ใส่ seed แบบสุ่มเพื่อให้ได้ภาพใหม่เสมอ
            seed = int(time.time()) + i
            url = f"https://pollinations.ai/p/{sc['image_prompt'].replace(' ', '%20')}?width=1080&height=1920&model=flux&seed={seed}"
            
            # พยายามโหลดจนกว่าจะได้รูป (Retry 3 ครั้ง)
            success = False
            for attempt in range(3):
                r = requests.get(url, timeout=30)
                if r.status_code == 200 and len(r.content) > 10000: # ต้องมีขนาดมากกว่า 10KB ถึงจะเป็นรูปจริง
                    with open(f"i_{i}.jpg", "wb") as f: f.write(r.content)
                    print(f"   📸 ฉากที่ {i+1}: โหลดสำเร็จ")
                    success = True
                    break
                print(f"   ⚠️ ฉากที่ {i+1}: กำลังลองใหม่ (รอบที่ {attempt+1})...")
                time.sleep(2)
            
            if not success: raise RuntimeError(f"❌ โหลดรูปฉากที่ {i+1} ไม่สำเร็จ")

        # 4. ประกอบวิดีโอ (ปรับปรุงคำสั่งให้เสถียรขึ้น)
        print("🎬 4. กำลังตัดต่อวิดีโอ...")
        # สร้างไฟล์รายการภาพ
        with open("l.txt", "w") as f:
            for i in range(3):
                f.write(f"file 'i_{i}.jpg'\nduration 5\n")
            f.write(f"file 'i_2.jpg'") # บรรทัดสุดท้ายไม่ต้องมี duration

        # ใช้คำสั่ง FFmpeg ที่บังคับ Format ให้ตรงกัน
        cmd = (
            "ffmpeg -y -f concat -safe 0 -i l.txt -i v.mp3 "
            "-c:v libx264 -pix_fmt yuv420p -r 25 -vf 'scale=1080:1920' "
            "-c:a aac -shortest final.mp4"
        )
        subprocess.run(cmd, shell=True, check=True)

        # 5. อัปโหลด
        print("🚀 5. อัปโหลดไป YouTube...")
        with open('token.json', 'r') as f:
            creds = YoutubeCredentials.from_authorized_user_info(json.load(f))
        
        youtube = build("youtube", "v3", credentials=creds)
        request = youtube.videos().insert(
            part="snippet,status",
            body={
                "snippet": {"title": data['topic'], "description": "Auto-generated by AI"},
                "status": {"privacyStatus": "private"}
            },
            media_body=MediaFileUpload("final.mp4")
        )
        res = request.execute()
        print(f"✨ สำเร็จแล้ว! คลิปของคุณอยู่ที่: https://youtu.be/{res['id']}")

    except Exception as e:
        print(f"\n‼️ พังตรงนี้ครับ: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    run_workflow()
