name: Auto YouTube Post
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # ใช้ 3.11 นิ่งที่สุด
      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install google-genai requests edge-tts google-api-python-client google-auth Pillow
      - name: Run Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
